[!] Program not found: seacrh
[!] Program not found: seacrh
[!] Program not found: 10.129.220.0/22
[!] Program not found: [show
[!] Program not found: seacrh
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/exploits/android_tools/adb Interface.py", line 249, in sys_call_Linux
    subprocess.run(dataList)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'exploit'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/exploits/android_tools/adb Interface.py", line 249, in sys_call_Linux
    subprocess.run(dataList)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
[!] Program not found: return
[!] Program not found: 6
[!] Program not found: exploit\
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/exploits/android_tools/adb Interface.py", line 249, in sys_call_Linux
    subprocess.run(dataList)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'recored_screen'
[!] Program not found: get-targets
[!] Program not found: get-targets
[!] Program not found: recon
[!] Program not found: view-targets
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 121, in check
    Wififuncs[WifiInputs.index(data.split(" ")[0])](data)
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/netToolAttacks/nmapWrapper.py", line 44, in show_target_list
    for x in self.targetlist:
             ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'targetlist'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 121, in check
    Wififuncs[WifiInputs.index(data.split(" ")[0])](data)
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/netToolAttacks/nmapWrapper.py", line 44, in show_target_list
    print(self.targetlist)
          ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'targetlist'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 124, in check
    Wififuncs[WifiInputs.index(data.split(" ")[0])](data)
TypeError: nmap.show_target_list() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 124, in check
    print(Wififuncs[WifiInputs.index(data.split(" ")[0])]())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donald/.SuperSploit/source/core/reconCore/networkRecon/netToolAttacks/nmapWrapper.py", line 56, in scan_whole_network
    if ip.index(x) < len(ip - 1):
                         ~~~^~~
TypeError: unsupported operand type(s) for -: 'list' and 'int'
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 106, in check
    data = fix[1].split(' ')
           ~~~^^^
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 107, in check
    data = fix[1].split(' ')
           ~~~^^^
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 107, in check
    data = fix[1].split(' ')
           ~~~^^^
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/donald/.SuperSploit/source/core/inputHandler.py", line 115, in check
    if data.endswith(" "):
       ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'endswith'
